version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - rm -rf node_modules package-lock.json
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://food-court-frontend --delete
      - echo Invalidating CloudFront...
      - aws cloudfront create-invalidation --distribution-id E3TLJY59YILXQL --paths "/*"

artifacts:
  files:
    - '**/*'
