version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - rm -rf node_modules package-lock.json
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://foodcourt-frontend-deployment-cicd-631534400893-ap-south-2-an --delete
      - echo Invalidating CloudFront...
      - aws cloudfront create-invalidation --distribution-id E2GXUKYKY3UTQ1 --paths "/*"

artifacts:
  files:
    - '**/*'
